version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - alpine:/usr/share/nginx/html/alpine
      - ./conf.d:/etc/nginx/conf.d
    restart: ${RESTART:-no}

  alpine:
    build:
      context: ./alpine
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
    volumes:
      - alpine:/alpine
    restart: ${RESTART:-no}

  pip:
    build:
      context: ./pip
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        PIP_INDEX_URL: ${PIP_INDEX_URL}
    ports:
      - 3141:3141
    volumes:
      - pip:/pip
    restart: ${RESTART:-no}

  npm:
    build:
      context: ./npm
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
        NPM_PROXY: ${NPM_PROXY}
    ports:
      - 8080:8080
    volumes:
      - npm:/npm
    restart: ${RESTART:-no}

volumes:
  alpine:
    driver: 'local'
  pip:
    driver: 'local'
  npm:
    driver: 'local'
