version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - alpine:/usr/share/nginx/html/alpine
      - ./conf.d:/etc/nginx/conf.d

  alpine:
    build:
      context: ./alpine
      args:
        ALPINE_SERVER: 192.168.11.200
    volumes:
      - alpine:/alpine

  pip:
    build:
      context: ./pip
      args:
        ALPINE_SERVER: 192.168.11.200
    ports:
      - 3141:3141
    volumes:
      - pip:/pip

  npm:
    build:
      context: ./npm
      args:
        ALPINE_SERVER: 192.168.11.200
    ports:
      - 8080:8080
    volumes:
      - npm:/npm

volumes:
  alpine:
    driver: 'local'
  pip:
    driver: 'local'
  npm:
    driver: 'local'
